/// <reference types="cypress" />
import { basicMenuComponents } from '../../support/basic-menu-components';

describe('Basic Menu Components', () => {
  const menu = [
    {
      id: 'dashboard',
      title: 'Hypster',
      menu: 'Dashboard',
      url: '/',
      header: true,
      headerText: 'Dashboard',
      headerSmall: false,
      headerSmallText: '',
      breadcrumb: 'Home',
      hasTreeview: false,
      child: [],
    },
    {
      id: 'data',
      title: 'Data',
      menu: 'Data',
      url: '#',
      header: false,
      heaederText: '',
      headerSmall: false,
      headerSmallText: '',
      breadcrumb: '',
      hasTreeview: true,
      child: [
        {
          id: 'customer',
          title: 'Customer',
          menu: 'Customer',
          url: '/customer/',
          header: true,
          headerText: 'Customer Data',
          headerSmall: true,
          headerSmallText: 'Data',
          breadcrumb: 'Customer',
        },
        {
          id: 'product',
          title: 'Product',
          menu: 'Product',
          url: '/product/',
          header: true,
          headerText: 'Product Data',
          headerSmall: true,
          headerSmallText: 'Data',
          breadcrumb: 'Product',
        },
      ],
    },
    {
      id: 'masterdata',
      title: 'Master Data',
      menu: 'Master Data',
      url: '#',
      header: false,
      heaederText: '',
      headerSmall: false,
      headerSmallText: '',
      breadcrumb: 'Master Data',
      hasTreeview: true,
      child: [
        {
          id: 'ph',
          title: 'pH',
          menu: 'pH',
          url: '/master-data/ph/',
          heaedr: true,
          headerText: 'pH Data',
          headerSmall: true,
          headerSmallText: 'Data',
          breadcrumb: 'pH',
        },
        {
          id: 'temperature',
          title: 'Temperature',
          menu: 'Temperature',
          url: '/master-data/temperature/',
          header: true,
          headerText: 'Temperature Data',
          headerSmall: true,
          headerSmallText: 'Data',
          breadcrumb: 'Temperature',
        },
      ],
    },
    {
      id: 'system',
      title: 'System',
      menu: 'System',
      url: '#',
      header: false,
      headerText: '',
      headerSmall: false,
      headerSmallText: '',
      breadcrumb: 'System',
      hasTreeview: true,
      child: [
        {
          id: 'user',
          title: 'User',
          menu: 'User',
          url: '/system/user/',
          header: true,
          headerText: 'User Data',
          headerSmall: true,
          headerSmallText: 'Data',
          breadcrumb: 'User',
        },
      ],
    },
  ]

  menu.forEach((curr) => {
    basicMenuComponents(
      curr.id,
      curr.title,
      curr.menu,
      curr.url,
      curr.header,
      curr.headerText,
      curr.headerSmall,
      curr.headerSmallText,
      curr.breadcrumb,
      curr.hasTreeview,
      curr.child,
    );
  })
});